### PR TITLE
Fix random negative amounts

### PR DESCRIPTION
**Pull request by CzEMC**
Sometimes, players will get negative amounts when bidding because their balance is not checked before money is withdrawn.

### CODE REVIEW

**Comment by Cnly** [comment]
Hi, I think `economy.withdrawPlayer` is supposed to return an `EconomyResponse`, which will state whether the transaction was successful. I was unable to replicate the 'negative amount' problem with my 1.12.2 server and economy provided by Essentials. Could you please provide some more details on your environment or how this can be replicated?

**Comment by CzEMC** [comment]
SaneEconomy, it is trusting that you are checking the player's balance before withdrawing because it will withdraw and make the player go into negative amounts. This is intentional and it is up to the developer to check before taking out.

**Comment by CzEMC** [comment]
But, here's the issue reproduced:

https://i.gyazo.com/0559b0b6ab168469b6a76f893803bfae.mp4

Result:
https://gyazo.com/54012fb7c47016d2d78f99b767259170

I believe the issue is that the plugin is calculating the fee incorrectly.

However, if I have $0, I cannot bid at all, so I have no clue what's up with it.

**Comment by Cnly** [comment]
Hi, I downloaded [SaneEconomy](https://www.spigotmc.org/resources/saneeconomy-simple-but-featureful-economy.26223/) 0.13.1 and tested on my machine, but I still couldn't reproduce your problem.

image

However, I did found that in early versions of SaneEconomy, it seemed to have some weird support for Vault... What version of SaneEconomy are you using?

**Comment by CzEMC** [comment]
I used an old version. I still get the issue, but i'll just make a balance checker/compile on my side.

**Pull request closed without merging**
